version: "2.3"
services:
  smartkotkot:
    image: "sylchauf/smart-kotkot:latest"
    restart: always
    security_opt:
      - seccomp:unconfined
    device_cgroup_rules:
      - "c *:* rmw"
    volumes:
      - ./state:/app/state
      - /dev:/dev
  caddy:
    image: caddy:2.4.3-alpine
    restart: always
    environment:
      - DOMAIN
    command: sh -c "caddy --http-port $$HTTP_PORT --https-port $$HTTPS_PORT reverse-proxy --from https://$$DOMAIN --to http://smartkotkot:3000"
    ports:
      - "${HTTP_PORT}:${HTTP_PORT}"
      - "${HTTPS_PORT}:${HTTPS_PORT}"
    volumes:
      - ./caddy:/data
    depends_on:
      - smartkotkot
