version: "2.3"
services:
  smartkotkot:
    image: "sylchauf/smart-kotkot-beta:latest"
    restart: always
    environment:
      - PORT=3000
      - MONGO_URL=mongodb://database:27017/smart-kotkot
      - ROOT_URL=http://YOUR_IP:8080
    ports:
      - "8080:3000"

  database:
    image: mongo:5.0.5
    restart: always
    volumes:
      - /opt/smartkotkot/data/mongodb:/data/db
    ports:
      - '127.0.0.1:27017:27017'

  watchtower:
    image: containrrr/watchtower
    restart: always
    environment:
      - WATCHTOWER_CLEANUP=true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 300
