version: "2.3"
services:
  smartkotkot:
    image: "sylchauf/smart-kotkot:latest"
    restart: always
    security_opt:
      - seccomp:unconfined
    device_cgroup_rules:
      - "c *:* rmw"
    volumes:
      - ./state:/app/state
      - /dev:/dev
