version: "2.3"
services:
  smartkotkot:
    image: "sylchauf/smart-kotkot:latest"
    restart: always
    security_opt:
      - seccomp:unconfined
    device_cgroup_rules:
      - "c *:* rmw"
    volumes:
      - ./state:/app/state
      - /dev:/dev
  caddy:
    image: caddy:2.4.3-alpine
    restart: always
    environment:
      - DOMAIN
    command: sh -c "caddy reverse-proxy --from https://$$DOMAIN:443 --to http://smartkotkot:3000"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./caddy:/data
    depends_on:
      - smartkotkot
