version: "2.3"
services:
  smartkotkot:
    image: "sylchauf/smart-kotkot:latest"
    restart: always
    environment:
      - PORT=3000
      - MONGO_URL=mongodb://database:27017/smart-kotkot
      - ROOT_URL=${PROTOCOL:-https}://${DOMAIN}

  caddy:
    image: caddy:2
    restart: always
    ports:
      - ${PORT:-80}:80
    volumes:
      - $PWD/Caddyfile:/etc/caddy/Caddyfile
      - /opt/smartkotkot/data/caddy/data:/data
      - /opt/smartkotkot/data/caddy/config:/config

  database:
    image: mongo:5
    restart: always
    volumes:
      - /opt/smartkotkot/data/mongodb:/data/db
    ports:
      - "127.0.0.1:27017:27017"

  go2rtc:
    image: alexxit/go2rtc:latest
    restart: always
    volumes:
      - $PWD/go2rtc.yaml:/config/go2rtc.yaml
